# Generated by Django 4.0.5 on 2022-06-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog_thumbnail_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Deepnote_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
