# Generated by Django 4.0.1 on 2022-06-13 15:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
